### ISSUE TITLE
Instructor using Student Header in instructorCourseJoinConfirmation.jsp

### ISSUE THREAD

**Issue by bamboo3250** [TEAMMATES/repo#3850] opened 2015-06-29 07:25 UTC
I need a confirmation to continue #3847. When an instructor going to Join Confirmation Page, should the navbar be shown as student's or instructor's? For now, even when the file name has prefix "instructor", it's still using STUDENT_HEADER. @kanghj @damithc

**Comment by damithc** [comment] 2015-06-29 07:28
I'm not familiar with this thing. @kanghj ?

**Comment by junhaoyap** [comment] 2015-06-29 07:41
I'm confident this is unintended, refer to screenshots attached ->

![screen shot 2015-06-29 at 3 39 43 pm](https://cloud.githubusercontent.com/assets/6291947/8403232/276331d8-1e75-11e5-9eee-90688c502d33.png)
![screen shot 2015-06-29 at 3 39 51 pm](https://cloud.githubusercontent.com/assets/6291947/8403231/27352036-1e75-11e5-96b5-ff343fa563e8.png)

**Comment by kanghj** [comment] 2015-06-29 07:41
The student header looks like its a mistake when the confirmation for instructors was first introduced, probably from copy and pasting the confirmation page for students

**Comment by junhaoyap** [comment] 2015-06-29 07:42
Note from above, I logged in as admin, created an instructor account and went to confirmation page, note that the navbar initially shows the student pages, but once I click and confirmed "yes this is my account", it became instructor navbar.

**Comment by bamboo3250** [comment] 2015-06-29 07:53
okay, thank guys @junhaoyap @kanghj. I will fix this in JSTL branch. It's surprising that no one notices this before.

**Comment by junhaoyap** [comment] 2015-06-29 07:56
That's why careful code review is important, just being too relaxed once can be really devastating, of course this isn't anything devastating :p

**Comment by damithc** [comment] 2015-06-29 08:57
Good catch @bamboo3250 :+1:

**Comment by bamboo3250** [comment] 2015-06-29 08:59
this one should be credited to @yj-soh. He did very well as a reviewer :+1:

**Comment by junhaoyap** [comment] 2015-07-01 03:02
This has been done by @bamboo3250 in the JSTL side, will be closing it.

**Closed by junhaoyap** 2015-07-01 03:02 UTC
Labels: a-AccessControl, a-Usability, t.Bug
