### ISSUE TITLE
process.md: typo/grammatically inconsistent phrase present

### ISSUE THREAD

**Issue by drunken-saint** [TEAMMATES/repo#2997] opened 2015-02-16 17:51 UTC
Under the 'Issue Labels' heading , under 'Type' sub heading , point for t.Enhancement , in brackets the phrase is not correct and 'story' is typed as 'stroy' .

**Comment by damithc** [comment] 2015-02-17 00:19
Duplicate of #2391

**Closed by damithc** 2015-02-17 00:19 UTC
