### ISSUE TITLE
# in session name gives problems

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#3184] opened 2015-03-21 17:35 UTC
So I tried making one session like this:
![3200_1](https://cloud.githubusercontent.com/assets/7261051/6766080/202a3906-d033-11e4-8dc7-566de12d2cb0.png)
Other settings (time, questions) are standard.
Then I went to the "comments" section on the navbar. Upon clicking this:
![3200_2](https://cloud.githubusercontent.com/assets/7261051/6766085/53c24088-d033-11e4-9752-9e31cc8bbd75.png)
Disaster happened:
![3200_3](https://cloud.githubusercontent.com/assets/7261051/6766087/63218f16-d033-11e4-928d-0feeb952034d.png)
I know for sure that what causes the problem is the '#' in the session name. However, I don't know if there are any other chars that can trigger this as well. Will update if I find more.

**Comment by damithc** [comment] 2015-03-22 15:19
@kai33 any advice?

**Comment by kai33** [comment] 2015-03-22 16:35
this can be resolved by:
in feedbackResponseComments.js,
in function loadFeedbackResponseComments,
change 
> var fsNameForUrl = fsName.split(' ').join('+');
to
> var fsNameForUrl = encodeURIComponent(fsName);

root cause:
no encode URI when invoke ajax call.

**Comment by wkurniawan07** [comment] 2015-03-22 16:41
I'll leave it to some other contributors, then.
@kai33 thanks for taking a look at this!

**Comment by kai33** [comment] 2015-03-22 16:42
Thank u for reporting this issue, it's really helpful to Teammates!

**Comment by acruis** [comment] 2015-04-01 10:01
Thanks Wilson and Kai Xie. I'm writing up the fix now.

**Closed** 2015-04-02 20:03 UTC
Labels: f.Comments, forContributors, p.Medium, s.Accepted, t.Bug
