### ISSUE TITLE
Remove GodModeTest from AllTests

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#3073] opened 2015-03-10 03:06 UTC
May be we can make the Godmode test pass even if the user accounts are the ones given in the test.properties is the same as the ones in the template?

**Comment by kai33** [comment] 2015-03-10 18:33
or we can update the test.template.properties to pass the test?
or explicitly mention the modification of default test accounts in settingUp.md?

**Comment by vamshi-s** [comment] 2015-03-11 00:00
@damithc 
In GodModeTest.java file, 
the following lines of code fetches data from the properties file.

testAccounts += TestProperties.inst().TEST_ADMIN_ACCOUNT;

I think i can add one line of code, which checks whether the string is ending with ".example" or not. If its ending with it, i wont do anything. If not we will write a method to append ".example" to that string. 
we need to repeat this procedure for all the lines of code, highlighted in the picture.

If we want me to proceed with changes, Please assign me this issue.
![untitled](https://cloud.githubusercontent.com/assets/11355301/6587851/c8fa01e2-c7af-11e4-9777-db8761686a53.png)

**Comment by damithc** [comment] 2015-03-11 03:01
@thyageshm what do you think?

**Comment by thyageshm** [comment] 2015-03-11 03:43
The whole idea of the test is to check if the presence of the accounts defined in the test.properties folder are being substitued in the web page. So adding a ".example" in the java file is not going to help. If anything, we should automatically add the '.example' in the test.properties file. 

The reason why we dont want to have the default accounts is because they occur in the same accounts that are given to the user or smth like that. So if GodMode is run with the default accounts (not the test even the ACTUAL Godmode), it will affect normal working of some files on the website

**Comment by LowWeiLin** [comment] 2015-03-11 03:50
Can we just remove the test from All Tests? It only needs to be run when changes are made to GodMode, which is usually only done by @thyageshm 
Removing it will also prevent failures that are sometimes caused by godmodeOutput.html

**Comment by damithc** [comment] 2015-03-11 03:56
I'm OK for removing it from the regular test suites. If we do, may be add a comment in the GodMode code to mention where the test is and it is not included in the regular test suite.

**Comment by thyageshm** [comment] 2015-03-11 03:57
I agree with that. We can simply remove it from the usual tests

On Wednesday, March 11, 2015, Damith C. Rajapakse <notifications@github.com>
wrote:

> I'm OK for removing it from the regular test suites. If we do, may be add
> a comment in the GodMode code to mention where the test is and it is not
> included in the regular test suite.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TEAMMATES/repo/issues/3073#issuecomment-78201232>.
>


-- 
Regards,
Thyagesh Manikandan

**Comment by mikelimantara** [comment] 2015-03-11 11:26
starting issue

**Comment by jarvis57** [comment] 2015-03-11 20:58
Hi, I completed the orientation tasks A-D. Can I be assigned to this issue?

Btw, just for sure, are you talking about dev server? Because for staging server, "if the user accounts are the ones given in the test.properties is the same as the ones in the template", lots of test will fail include the godMode test.

**Comment by LowWeiLin** [comment] 2015-03-12 03:35
@jarvis57 This one already has a pull request. Do look for another issue.

**Closed** 2015-03-12 13:47 UTC
Labels: a-Testing, forFirstTimers, p.Low, s.Accepted, t.Task
