### ISSUE TITLE
Jumping to instructor help page anchor leaves content behind fixed header

### ISSUE THREAD

**Issue by taniach** [TEAMMATES/repo#3238] opened 2015-04-01 05:30 UTC
![anchor1](https://cloud.githubusercontent.com/assets/7547452/6935149/0ded4114-d873-11e4-856c-aa552dd81b02.jpg)
![anchor2](https://cloud.githubusercontent.com/assets/7547452/6935150/0e0bb61c-d873-11e4-9aed-74ef29e0d1df.jpg)
![anchor3](https://cloud.githubusercontent.com/assets/7547452/6935151/0e1cd550-d873-11e4-9d0c-283ebc3f54d3.jpg)

**Comment by LowWeiLin** [comment] 2015-04-01 09:12
Duplicate of #2337

**Closed by LowWeiLin** 2015-04-01 09:12 UTC
Labels: a-Docs, d.Moderate, p.Medium, s.Accepted
