### ISSUE TITLE
InstructorFeedbacks: email options are not preserved when the session creation fails

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#1762] opened 2014-05-02 13:26 UTC
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on March 30, 2014 19:07:16_

When the instructor submits the session creation form and it is rejected due to some error in the data (e.g. start time is after end time), the email options previously entered are not preserved in the reloaded form.

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1765_

**Comment by kanghj** [comment] 2016-02-10 11:38
Duplicate of #3777

**Closed by kanghj** 2016-02-10 11:38 UTC
Labels: a-UIX, c.Bug, c.Enhancement, d.Contributors, f-Submissions, p.Medium
