### ISSUE TITLE
Help students who forgot which Google ID they used for TEAMMATES

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#775] opened 2014-05-02 10:24 UTC
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on May 02, 2013 08:00:57_

Some students have multiple Google IDs and cannot remember which one they used for TEAMMATES

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=776_

**Comment by MrFool** [comment] 2015-06-26 07:41
Duplicate of #1259 and it has more discussion there so let's close this

**Closed by MrFool** 2015-06-26 07:41 UTC
Labels: d.Difficult, f.Courses, p.Low, s.Accepted, t.Enhancement
