### ISSUE TITLE
Users go to old home page when trying to submit for new course

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4572] opened 2015-11-13 23:41 UTC
I have several cases of this.
A student receives a link from a new course.
After clicking on the link, students ends up in his/her home page which shows his previous courses but not the new one.
Some reported seeing the 'expired login' message in the home page. So students get redirected to home page because TEAMMATES detects an expired login.

**Comment by damithc** [comment] 2015-11-13 23:41
@thyageshm can have a look?

**Comment by thyageshm** [comment] 2015-11-14 06:36
ok!

**Comment by thyageshm** [comment] 2015-11-14 07:13
Sir I have a few clarifications to make.

1. Could I have one such link that caused this problem? The "expiry" message comes in when a post parameter is null. Just want to see if the link was malformed.
2. did this happen when they submit a feedback for the course or when they try to join a course? 
3. Is this happening for a particular course or many different courses?
4. Since when have these cases been arriving?

Thanks!

**Comment by damithc** [comment] 2015-11-14 08:57
1. Here is the message in log (some details changed)
Redirecting user to /logout.jsp?next=%2Fpage%2FstudentFeedbackSubmissionEditPage%3Fcourseid%3D2015-ModA-SMIB1-GStrategy%26fsname%3DManagement%2BBehavior%2BAssessment%26key%3D216CEABC2E31655D8616C352B81A1C7D322F6D73156D620837CE1C625AFA0CAA17EB86E4186A6F95E80689194747E4ADAAF8C8D3733A50182BA805335714C19B%26studentemail%3Doabcov2016%2540student.hult.edu&user=ABCC6E86CD256B4AA1EE579663838817

2. Submit
3. Several different courses
4. I've had about 3-4 cases in the last week or so. I usually ask them to use a different browser and it seems to work.

**Comment by thyageshm** [comment] 2015-11-14 15:13
I see... so the students have already joined the course but are unable to submit responses. When they try to submit the responses, they are redirected to the home page and the entire course is missing?

**Comment by damithc** [comment] 2015-11-15 01:52
No the student has not joined the course in concern yet but has joined other courses before.

**Comment by thyageshm** [comment] 2015-11-15 06:50
Sir, our student users get a feedback session link for a new course via email. When they click on such a link, the student entity does not get linked to the currently loggedin user (we did this because we had cases of students sharing the same computer and automatically associating the google id with the student entity was a problem). Thus the system logs the user out and considers her as an unregistered student. Thus, unless the user clicks on the link on the blue box at the top of the page to "register" themselves with TEAMMATES, this course does not appear on their home page. 

For the current issue of redirecting to home page, I would like to know if there is a log where the user is redirected to the logout page but the next link is FstudentFeedbackSubmissionEditSave. If yes, then I have a possible cause for this problem.

**Comment by damithc** [comment] 2015-11-15 07:26
In the example link I gave above, the student ended up in the Home page (based on the admin activity log, the next page student accessed was the home page). Unfortunately, I cannot access that part of the log again because of the 24 hour limit.

**Comment by thyageshm** [comment] 2015-11-15 07:42
I see.
sir I think you can provide a date range for the log search. That way the 24 hour limit is not implemented

**Comment by damithc** [comment] 2015-11-15 07:59
I used a legit submission link from a student had this problem to test.
[Using IE11] Logged into my Gmail account first and then visited the link. Did not logout as expected and I was able to see the submission page. When I click on the the 'login using a google account' link it when to the permissions page of my Google account, asking me if I wish to let TEAMMATES access Google account authentication.

[Using FF 42] Logged into my Gmail account first and then visited the link. Logout as expected and went straight to my Google login page. When I logged in again, it went to TEAMMATES home page. However, the course did not appear in there. I think this is what happened to the students. Here is the redirect link shown during the Google login https://accounts.google.com/ServiceLogin?service=ah&passive=true&continue=https%3A%2F%2Fappengine.google.com%2F_ah%2Fconflogin%3Fcontinue%3Dhttps%3A%2F%2Fteammatesv4.appspot.com%2Fpage%2FstudentFeedbackSubmissionEditPage%253Fcourseid%253DCG3002-AY1516S1&ltmpl=gm&shdf=ABCLEgZhaG5hbWUaG1RFQU1NQVRFUyBQZWVyIEV2YWwuIFN5c3RlbQwSAmFoIhTnDgknr4LhGCQfgSMWpsXRMMHsVygBMhRgysb6Y9VWuFBW1ceJ2jJRww_Z3w

**Comment by thyageshm** [comment] 2015-11-16 09:30
Sir the redirect link looks wrong as the continue url does not have the feedback session name. There are a few places that the redirect happens in Action.java. All of them ensure that the parameters sent in as part of the initial link are forwarded throughout. Hence it is a little confusing to see that the feedback session parameter is missing here. The most probable cause of the issue we are facing is that over the multiple redirects that google does internally during the logout/login process, the continue url is being wrongly reconstructed from the url parameter. This dropping of parameters would trigger a redirection to the home page for loggedin users.

Sir is it possible to provide the chain of redirects that happened from the time the link was clicked for the first time? Like all the TEAMMATES pages the user visited until she ended up in the home page? Thank you!

**Comment by damithc** [comment] 2015-11-16 09:42
Are you referring to my most recent comment above about my test using FF 42? I was using the link that was sent to her. The comment contains all I did. There were no other pages involved. I repeated the step just now with the same result. Looks like two redirects happen but it's too fast to catch.

**Comment by damithc** [comment] 2015-11-16 09:54
I emailed you a legit submission link just now for you to test against the live server. Use firefox to test.

**Comment by damithc** [comment] 2015-11-16 13:49
More and more cases of this. e.g. CS2101 students are facing this problem because they are already registered in CS2103.

**Comment by damithc** [comment] 2015-11-16 14:10
The workaround for now is to logout from the Google account first before clicking on the link.

**Comment by thyageshm** [comment] 2015-11-16 14:39
I am looking into the link right now. 
Yes, I am referring to the FF 42 case. Any logs registered for the pages? I mean from the admin log entries?

**Comment by thyageshm** [comment] 2015-11-16 15:47
Sir, I think I have figured out what the problem is.

Step 1: the user logs in to TEAMMATES using her google account. 
Step 2: user clicks on the submit link we gave.
Step 3: TEAMMATES redirects user to logout link and sets the continue attribute to the submit page. This is based on the logic on lines 240 to  247:
```
     else if (isPageNotCourseJoinRelated() && doesRegkeyBelongToUnregisteredStudent() && isUserLoggedIn) {
                Url redirectUrl = new Url(Const.ViewURIs.LOGOUT)
                                      .withParam(Const.ParamsNames.NEXT_URL, requestUrl)
                                      .withUserId(StringHelper.encrypt(account.googleId)); 
                
                setRedirectPage(redirectUrl.toString());
                return null;
            }
```
Note: at the logout stage, one of the urls looks like this (details altered for anonymity): 
```http://www.google.com/accounts/Logout2?ilo=1&ils=ah&ilc=2&continue=https%3A%2F%2Fappengine.google.com%2F_ah%2Flogout%3Fcontinue%3Dhttps%3A%2F%2Fteammatesv4.appspot.com%2Fpage%2FstudentFeedbackSubmissionEditPage%3Fcourseid%3Ddamith.gma-demo2%26fsname%3Dfeedbacksession%26key%3Dregkeyoftheuser%26studentemail%3Dstudentemail&zx=295569630```
Notice that all our parameters are still intact

Step 4: Google goes through its logging out process (redirecting multiple times in the process) and then finally comes back to the app engine page (not TEAMMATES yet...)
Link at this stage looks like this:
```https://appengine.google.com/_ah/logout?continue=https://teammatesv4.appspot.com/page/studentFeedbackSubmissionEditPage?courseid=damith.gma-demo2&fsname=feedbacksession&key=regkeyoftheuser&studentemail=studentemail```

Notice that all our parameters are still intact BUT they are not html url encoded. Thus all parameters except courseid are considered as part of the appengine url rather than the continue url.

Step 5: Finall when it reaches TEAMMATES again, all parameters except courseid have been truncated.
link looks like:
https://teammatesv4.appspot.com/page/studentFeedbackSubmissionEditPage?courseid=damith.gma-demo2

Step 6: Since regkey is missing, TEAMMATES redirects the user to the login page based on the logic on lines 210 to 213:
```
        if (userIsNotLoggedIn && (userNeedsGoogleAccountForPage || noRegkeyGiven)) {
            setRedirectPage(Logic.getLoginUrl(requestUrl));
            return true;
        }
```

Step 7: When user logs in this time, TEAMMATES realises that fsname parameter is missing and hence throws a NullPostParameterException which the ControllerServlet catches and redirects the user to the home page with the "expiry" message.

**Comment by thyageshm** [comment] 2015-11-16 15:59
I think a way to solve this problem is to introduce a way to encrypt the entire parameter string in the url into a single parameter and pass it to the logout url.
Eg: convert: 
?courseid=asfd&fsname=fdsa&key=123dsf&studentemail=fd@fdswe.com
to:
?enc_param_list=asdfoifncnawoifehonjaslkdnff8hv2voidsmvc94

And in our Action.java, if we find this param in the url parameter list, we decrypt it and use the individual parameters.

@damithc what do you think?

**Comment by damithc** [comment] 2015-11-16 23:50
Yes, we can try that, although it will make troubleshooting harder because the encrypted string is not human readable. Another question is why is this happening now but not before. Anyway, we need to fix this fast.

**Comment by damithc** [comment] 2015-11-17 00:44
I suspect it affects anybody who is logged into Google but not registered in TEAMMATES. If that is the case, we are in big trouble. In that case this becomes a critical issue.

**Comment by damithc** [comment] 2015-11-17 02:19
@LowWeiLin @kanghj @wkurniawan07 can pitch in?

**Comment by LowWeiLin** [comment] 2015-11-17 02:53
Could this issue be due to upgrading the sdk version? There are similar reports of parameters being lost due to encoding of the url.
Encoding the url is a possible way, but we will have to ensure that it is either the first or only parameter.
It won't fix existing links that are already sent out though.

**Comment by thyageshm** [comment] 2015-11-17 03:41
@damithc sir, it affects anyone who is currently logged in to TEAMMATES via a google account and clicks on the link. 
Yes it is true that it wont be human readable, but it helps to condense all the parameters into one string. Another way would be to change all the '&' in the parameter string into another character and change it back after the logout is successful.

**Comment by thyageshm** [comment] 2015-11-17 03:46
@LowWeiLin I think we have been using the newer SDK in the live server for a while now. I doubt that it is the cause. Unless the problem has been there for a long time but the conditions needed for it to surface only happened recently.

**Comment by thyageshm** [comment] 2015-11-17 03:49
@damithc sir, since this issue only happens if the user is logged in to TEAMMATES with his google account, one way would be for us to automatically send the user to the course join page if such a situation happens, instead of logging him out.

**Comment by thyageshm** [comment] 2015-11-17 03:57
Also, the login routine works fine. That is, if the user clicks on the "link with google account" link given in the blue box at the top, the system automatically connects the google account with the student. Also, if the user clicks on the link and is not logged in (but registered before), the system correctly redirects her to the login page and then back to the submit page properly. So this issue is only for the logout case. And in particular, only if the user is logged in to TEAMMATES using a google account and tries to click on a feedback session link from a NEW course.

**Comment by thyageshm** [comment] 2015-11-17 04:04
To complete the loop, we can add a status message in studentCourseJoinConfirmation.jsp page that tells the user that "if she came to the link because of a submit page link and does not wish to register, she can logout using the link on top-right hand corner and click on the link in the email again."

This message is only shown if we realise that the next_url link in the course join page is a submit page.

**Comment by damithc** [comment] 2015-11-17 05:53
So the suggested solution doesn't need encrypting the parameters and will work for links sent out already?
Is there a standard way to encode the `&` in URLs? May be we are supposed to encode it anyway when giving a URL as a parameter?

**Comment by junhaoyap** [comment] 2015-11-17 06:03
We can try encoding it into percentage entities and see whether that solves the problem

**Comment by wkurniawan07** [comment] 2015-11-17 06:57
I've tried it on my staging, what @thyageshm claimed are all correct. The situation for replication is very specific, i.e someone who is logged in with a different account than the one used in submission link, and the account used in the submission link is not registered with the new course. Nothing to do with SDK version because it also happens on 5.38 (the instance I deployed when I first set up back then).

Encoding very likely won't work (if it isn't in place already). See [the explanation above](#issuecomment-157074874), in particular step 3: the URL is _already_ encoded, but Google decided to decode it back.

The ideal solution I have in mind is re-directing to course join authenticated link:
1. If the user is logged in with a different account, we will see this page (and this is a correct behavior):
![image](https://cloud.githubusercontent.com/assets/7261051/11204567/36907456-8d3b-11e5-9d31-d352cdfd06ee.png)
2. If the user is logged in with the same account, then it will join automatically and problem is solved.

**Comment by damithc** [comment] 2015-11-17 07:10
I'm ok with redirecting to the 'join' page.

**Comment by thyageshm** [comment] 2015-11-17 07:11
@damithc yes the suggested solution does not need encryption and works for the links that have already been sent out. We can take our time later in another issue to look into the encryption of parameters as it would take more time and needs changes in more places than the currently suggested one.
@wkurniawan07 thanks for the visuals! On top of the usual messages shown in the box, we can add the comment that if the user is seeing this page via a submit link, and does not wish to register, she can logout and try the link in the email again

**Comment by thyageshm** [comment] 2015-11-17 07:23
Steps to fix this issue:
1. In Action.java, the *redirectUrl* in line 241 must be made similar to the *joinUrl* in line 232.

**Comment by damithc** [comment] 2015-11-18 09:04
BTW, does that page has a logout link on the right hand corner?

**Comment by thyageshm** [comment] 2015-11-18 09:31
yup
![image](https://cloud.githubusercontent.com/assets/5160137/11237331/25783098-8e1a-11e5-8609-d1fdbcdac2f7.png)

**Comment by thyageshm** [comment] 2015-11-19 01:53
thanks @wkurniawan07

**Comment by damithc** [comment] 2015-11-20 13:25
This doesn't affect when unregistered users are trying to view results?

**Comment by wkurniawan07** [comment] 2015-11-20 13:28
It will, under the same condition for replication.

**Comment by damithc** [comment] 2015-11-20 13:30
OK, as long as both cases are being fixed.

**Closed** 2015-11-24 13:27 UTC
Labels: f.Courses, p.Urgent, t.Bug
