### ISSUE TITLE
NPE in search

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2913] opened 2015-01-21 23:56 UTC
java.lang.NullPointerException
	

Request Path /page 
Request Parameters {searchstudents::true, searchcommentforresponses::false, user::abc, searchkey::Nuria, searchcommentforstudents::false} 
Stack Trace

java.lang.NullPointerException
	at org.apache.jsp.jsp.instructorSearch_jsp._jspService(instructorSearch_jsp.java:376)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:97)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:327)
	at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:126)
	at teammates.ui.controller.ShowPageResult.send(ShowPageResult.java:57)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:59)
	at teammates.ui.controller.ControllerServlet.doGet(ControllerServlet.java:37)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:142)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:35)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:254)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:484)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:438)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:445)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:220)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:309)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:301)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:442)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:251)
	at java.lang.Thread.run(Thread.java:724)

**Comment by damithc** [comment] 2015-01-21 23:58
@imouto1994 can you have a look?

**Comment by imouto1994** [comment] 2015-01-22 05:27
Sure prof :)

**Comment by imouto1994** [comment] 2015-01-22 07:52
Sorry prof, do we have any other information about this student 'Nuria' from this course ? It is hard to know where the NPE happens from the stack trace

**Comment by damithc** [comment] 2015-01-22 08:57
The NPE is coming from the jsp page. `instructorSearch_jsp.java:376` I can't seem to find the said file though (it is the compiled version of the jsp page). That instructor gets that error for any student search, not just that particular student. @kai33 any ideas?

**Comment by damithc** [comment] 2015-01-22 09:03
Instructors of the same course can search for that student without a problem. So it is something specific to that instructor.

**Comment by imouto1994** [comment] 2015-01-22 10:38
One of the possible reason I can think of is that this 378th line `InstructorAttributes instructor = data.studentSearchResultBundle.instructors.get(student.course);` assigns null value for `instructor` variable.
However, according to the logic, this should always have corresponding value. I will try to look into it more.

**Comment by damithc** [comment] 2015-01-22 13:00
May be add some assertions in those places? At least it'll tell us where
the null is. I can deploy the new version (with assertions) and try it on
problematic user's data.

**Comment by kai33** [comment] 2015-01-22 13:36
I'm able to re-produce the bug:
1. Instructor A create a course with id 'course1'
2. Instructor B create a course with id 'course1.name', and enrol a student with name 'ABC'
3. Instructor A then search for 'ABC' --> exception occurs.

The cause:
1. google's full text search engine splits text like 'course1.name' into 'course1' and 'name'.
2. thus when search for text like 'course1' the engine will search for 'course1' and 'course1.name' (other instructor's course).

**Comment by kai33** [comment] 2015-01-22 13:45
My suggestion is,
to make a hotfix to filter the courseId again when get back the search result (currently in CommentSearchResultBundle, FrcSearchResultBundle, & StudentSearchResultBundle).

**Comment by damithc** [comment] 2015-01-22 14:07
Not sure if that is the cause though.
For example, this student is in two courses: FMIM1 and FMIM1-2
Searching for that student causes the error in the problematic instructor
(she is an instructor of only FMIM1) but no error when searched by another
instructor (he is an instructor of both courses).
Does this situation fit the suspected bug?

**Comment by imouto1994** [comment] 2015-01-22 14:12
Yes, I think it quite fits. The instructor of only FMIM1 will have the NPE when a student from FMIM1-2 is in the search results. Since the course FMIM1-2 is not in the list of instructors of the user's `googleID`, it will return a null value

**Comment by damithc** [comment] 2015-01-22 14:34
So text search splits by dash as well?

>

**Comment by imouto1994** [comment] 2015-01-22 14:38
Yes I think. I did some search on the GAE Search and found that they stated `The string is split into tokens wherever whitespace or special characters (punctuation marks, hash sign, etc.) appear`. This problem can be fixed by having a pre-filter for each student :)

**Closed** 2015-01-24 03:50 UTC
Labels: f.Search, p.High, s.Accepted, t.Bug
