### ISSUE TITLE
Sending invites before the evaluation opens can puzzle students because there is nothing for them to do when they join the course.

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#1303] opened 2014-05-02 11:50 UTC
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on December 03, 2013 09:20:05_

We warn the instructor before sending invites, but some instructors still send invites. May be there is a way around this?

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1304_

**Comment by damithc** [comment] 2015-01-07 14:21
We can inform the student if he/she joins a course that doesn't have any sessions.

**Comment by thyageshm** [comment] 2015-01-21 13:14
sir, should we handle this by providing a message at the student home page to update their profile (similar to the new user message for instructors) when there are no sessions to be done? We could have a smarter algo to check if the profile has already been updated (ie existing user) from the really new ones

**Comment by damithc** [comment] 2015-01-21 14:28
@kanghj this may be related to #2891 ?

**Comment by kanghj** [comment] 2015-01-21 15:27
Yes, this looks like a duplicate of #2891

**Comment by damithc** [comment] 2015-01-22 00:18
Note that this needs a bit more than simply asking to fill in the profile.
Can do both together?

**Comment by kanghj** [comment] 2015-01-22 14:59
![newstatusmsg](https://cloud.githubusercontent.com/assets/2216119/5857808/66fb912c-a289-11e4-8432-d07dc47eedec.PNG)

Just to give an update and clarify, is this what the student should see after clicking on the link sent in the email and authenticating? (The last line about updating profile will only appear if the student has not modified his profile before)

I am still working on the smarter logic to determine if the profile has been modified before.

**Comment by damithc** [comment] 2015-01-22 15:04
Looks good. May be show both course ID and course name in the status message. The course ID used in TEAMMATES may be different from the one they use in the school which might confuse students.

**Comment by thyageshm** [comment] 2015-01-24 07:30
Looks great. I believe the profile has a "modifiedDate" attribute that can be used for this purpose. Also,  we could check if any of the "important" fields have been left out and provide a message thats more tailored to the user. Eg: "Meanwhile, you can provide a preferred name that you would like to be addressed by your instructors here"

**Comment by kanghj** [comment] 2015-01-25 02:19
Ok, I will work on tailoring the message based on which attributes are missing in the profile. 

Meanwhile, this is the logic for showing the message about updating the profile.
If the account is newly created, show the message. 
Otherwise, 
    compare the profile's modified date with the account's creation date, and show the message if they are within a time period (a few minutes) of each other. 

However, I realised that the above logic might not be good enough. It will not work for legacy accounts that did not have student profiles when the accounts were created. 

An alternative is simply to show the message if the profile was not updated in the past day. 


Testing the message for updating profile is also giving me some trouble as I am unable to set the modifiedDate when creating student profiles. It is always set to the current date when toEntity() is called. Therefore, I cannot create a situation where the modifiedDate is set to a date prior to the student joining the course.

**Comment by thyageshm** [comment] 2015-01-25 07:25
I see... then a simple way would be to check if there are any fields in the profile that are empty and show the message correspondingly.

This could be achieved by having a method in ProfileAttributes class: generateUpdateMessageForStudent()

This can return a string based on the fields that are empty:
1. if more than one field is empty, use a generic message
2. If exactly one is empty, use a specific message
3. (optional) you can consider having a list of more important fields and only generate messages based on the status of those fields

**Comment by thyageshm** [comment] 2015-01-25 07:26
Also, could you open an issue to address the problem of modifiedDate in the student profile?

**Closed** 2015-02-01 08:07 UTC
Labels: a.Usability, d.Moderate, f.Profiles, p.Low, s.Accepted, t.Enhancement
