### ISSUE TITLE
InstructorFeedbackResultsPageUiTest failing on line 221

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#3253] opened 2015-04-02 17:04 UTC
I'm unable to pass it even after several runs. It's failing under the segment <code> ______TS("test view photo for view by questions"); </code> 
on <code>resultsPage.hoverClickAndViewGiverPhotoOnTableCell(0, 0, "studentProfilePic?studentemail={*}&courseid={*}&user=CFResultsUiT.instr");</code> 

It's failing due to 
<code>org.openqa.selenium.WebDriverException: document.getElementsByClassName(...)[0] is undefined</code>

This line was added in #3028.

**Comment by LowWeiLin** [comment] 2015-04-03 03:36
This is passing for me. Likely due to timing issues.

**Comment by MrFool** [comment] 2015-04-06 17:06
I'm having the same issue on latest master even after multiple tries as well, commented out and every other tests passes

**Comment by MrFool** [comment] 2015-05-21 07:53
Closing, duplicate of #3443 which will have it fixed via executing JavaScript

**Closed by MrFool** 2015-05-21 07:53 UTC
Labels: f.Sessions, s.Accepted, t.Bug
