### ISSUE TITLE
Reduce number of HTML verification tests

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/repo#3321] opened 2015-04-13 16:29 UTC
HTML verification tests are fragile and there are too many of them - sometimes after adding a small feature a huge number of them needs to be changed.

Should we reduce their usage and only use them when absolutely necessary?

**Comment by damithc** [comment] 2015-04-14 00:34
Indeed we should not have *any* test unless it is absolutely necessary, UI
tests in particular because they are expensive. The purpose of UI tests is
to catch regressions in the UI generation logic and client-side
interactions. UI tests should not be used to test other things.

**Comment by MrFool** [comment] 2015-04-14 07:59
So the reason why I opened this issue is because of #3302 where I was fixing #1733 and simply adding a button to cancel editing required the change of a whooping 36 files :p

I believe there are some UI tests that can be made to do web element checking etc. instead of full .verifyHTML("...") thus I'm suggesting that we look into some of the verifyHTML and see where it can be changed to WebElement checks or other less expensive checks

**Comment by damithc** [comment] 2015-04-14 08:11
yes, we should definitely do that.

**Comment by damithc** [comment] 2016-02-06 14:42
UI tests are much more robust now. closing.

**Closed by damithc** 2016-02-06 14:42 UTC
Labels: a-Testing
