### ISSUE TITLE
InstructorFeedbackEditPage: display warnings just above the  invalid question

### ISSUE THREAD

**Issue by JosephineKwa** [TEAMMATES/repo#2947] opened 2015-01-30 11:43 UTC
When an attempt is made to save a question with invalid fields, the page jumps to the top and displays the warning there. I feel that perhaps it would be clearer to display warnings just above the question that gave the warning.

**Comment by damithc** [comment] 2015-01-31 19:18
Good suggestion @JosephineKwa  
Duplicate of #1049

**Closed by damithc** 2015-01-31 19:18 UTC
